import type { Metadata } from "next";
import "../../globals.css";
import { Inter } from "next/font/google";
import Menu from "@/components/shared/Menu";
import Navbar from "@/components/shared/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "University Campus Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row`}>
        <Menu role="teacher" />
        <div className="min-h-screen bg-gray-100 ml-[300px]" style={{ width: "-webkit-fill-available" }}>
          <Navbar role="teacher" />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
